### ISSUE TITLE
Question about miss './run/'

### ISSUE THREAD

**Issue by qiuqicao77** [kenziyuliu/DGNN-PyTorch#1]
To test some model weights (by default saved in ./runs/); However, there is no run folder in the project. Can you share the model weight; Thanks!!!!

**Comment by kenziyuliu** [comment]
Hi qiuqicao77,

I have uploaded the best performing model I was able to reproduce for the Spatial stream in the `runs/` folder. To test it, you could do `python3 main.py --config ./config/nturgbd-cross-subject/test_spatial.yaml --weights runs/ntu_cs_dgnn_spatial-63-80128.pt` (or use any other options)
