### ISSUE TITLE
bone_data.npy file for Kinetics?

### ISSUE THREAD

**Issue by JasOlean** [kenziyuliu/DGNN-PyTorch#10]
Could you provide me bone_data.npy file for kinetics data? Because when I extract this file, I got segmentation error.

**Comment by kenziyuliu** [comment]
Hi, 

Bone data should be first generated from Joint data of Kinetics skeleton (which I didn't implement).
I just added `gen_bone_data.py` in `data_gen/` which should give you a useful place to start.
