### ISSUE TITLE
请问一下 我跑出的准确率为什么特别低 才80左右？空间流

### ISSUE THREAD

**Issue by dangao250** [kenziyuliu/DGNN-PyTorch#16]
Excuse me, why is the accuracy rate of my running out so low? Only about 80? Space flow

**Comment by dangao250** [comment]
可以给邮箱 请教几个问题吗

**Comment by dangao250** [comment]
Can you give me an email?

**Comment by ltw18** [comment]
> Excuse me, why is the accuracy rate of my running out so low? Only about 80? Space flow

你好，你解决了吗？这个代码给出的准确率只有85%，原文中接近90%，不知道原因

**Comment by kenziyuliu** [comment]
Hi there, unfortunately, I was not able to reproduce the reported accuracy of the paper. Given that I do not have spare hardware capacity for this, I think a good direction to investigate is https://github.com/kenziyuliu/DGNN-PyTorch/blob/master/model/dgnn.py#L52 where it was assumed that the temporal conv layers are shared between node/edge features (i.e. try using separate temporal layers)
