### ISSUE TITLE
请问您为什么你的关节预处理的结果 跟2sagcn的差别很大 不一样为什么

### ISSUE THREAD

**Issue by dangao250** [kenziyuliu/DGNN-PyTorch#17]
May I ask why your joint pretreatment results are very different from 2sagcn? Why?

**Comment by kenziyuliu** [comment]
Hi there, most preprocessing files are copied directly from 2s-AGCN, including the joint data preprocessing logic. You can verify this by running diff on the files in `data_gen/` to those in https://github.com/lshiwjx/2s-AGCN/tree/master/data_gen.
