### ISSUE TITLE
Thank you for your selfless dedication! Have you applied directed graphs to the Kinetics dataset?

### ISSUE THREAD

**Issue by 15762260991** [kenziyuliu/DGNN-PyTorch#29]

**Comment by 15762260991** [comment]
Your help would be appreciated！ @kenziyuliu

**Comment by kenziyuliu** [comment]
Hi @15762260991, thanks for your interest! No I haven't tried on Kinetics for this repo. But checkout https://github.com/kenziyuliu/MS-G3D which has support for Kinetics; hopefully it's not too hard to port this over.

**Comment by 15762260991** [comment]
@kenziyuliu I will try, thanks for your guidance!
