### ISSUE TITLE
Requirement for NTU-RGBD datasets

### ISSUE THREAD

**Issue by cuiqiongjie** [kenziyuliu/DGNN-PyTorch#3]
Because the official website has been in error, can I get  the NTU-RGBD dataset from baidu disk/ dropbox? email: cuiqiongjie@njust.edu.cn

**Comment by Anirudh257** [comment]
@cuiqiongjie You can mail the LIU JUN or the other authors mentioned in the paper.

**Comment by kenziyuliu** [comment]
You can download the datasets from here: http://rose1.ntu.edu.sg/Datasets/download3.asp (just checked that it works). You may need to request access from the lab though.
