### ISSUE TITLE
Motion data is used in kinetics-dataset?

### ISSUE THREAD

**Issue by JasOlean** [kenziyuliu/DGNN-PyTorch#4]
When I see config files, I found that there are two yamls : spatial and motion for NTU and joint and bone for Kinetics.
So, why do not use motion data in kinetics yaml config file? 
But, in your paper, you compared three methods for both NTU and Kinetics : spatial, motion and fusion for both dataset.
Please explain to me. Thank you.

**Comment by kenziyuliu** [comment]
Thanks for the issue. I haven't yet implemented the motion stream for the Kinetics dataset, please feel free to add to it. It should be similar to the generation of joint data.

BTW I'm not an author of the paper, and this repo provides an *unofficial* implementation.
