### ISSUE TITLE
Why ensemble accuracies are unstable?

### ISSUE THREAD

**Issue by JasOlean** [kenziyuliu/DGNN-PyTorch#5]
When I ensemble joint and bone score for every epoch, their accuracy is varying.
I mean although same epoch score, different accuracy result.
Why happened like that and how to fix it?

**Comment by Anirudh257** [comment]
Check https://github.com/lshiwjx/2s-AGCN/issues/10 if that helps.

**Comment by JasOlean** [comment]
I cannot understand Chinese words, could you explain me how to fix it? @Anirudh257

**Comment by Anirudh257** [comment]
You can use Google translate :)

**Comment by kenziyuliu** [comment]
Make sure you are ensembling the right scores for the right dataset, and not include any randomness on the testset when producing the classification scores

**Comment by RayLeijingsi** [comment]
> I cannot understand Chinese words, could you explain me how to fix it? @Anirudh257

in ensemble.py,  you can find that label[0], r1[0] and r2[0] are different. they are must be same. so, 'label', 'r1' and 'r2' need to be sorted.  i hope it helps you.

**Comment by JasOlean** [comment]
@RayLeijingsi 
Very thank you Ray, Now I fix that.
