### ISSUE TITLE
How can I train on selected classes?

### ISSUE THREAD

**Issue by IssaIssa1** [kenziyuliu/DGNN-PyTorch#7]
How can I train the DGNN on selected number of classes using NTU dataset instead in training it on all the data?

**Comment by kenziyuliu** [comment]
You may need to regenerate the data from the raw skeletons and filter out the unwanted classes, and train on the filtered data.

See this line in `ntu_gen_joint_data.py`:
```
action_class = int(filename[filename.find('A') + 1:filename.find('A') + 4])
```
